# Generated by Django 5.1.3 on 2025-01-03 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickelmodelsetting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickelmodelsetting',
            name='file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
