# Generated by Django 5.1.3 on 2025-01-03 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pickelmodelsetting', '0002_pickelmodelsetting_file_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickelmodelsetting',
            name='file_path',
        ),
    ]
