# Generated by Django 5.1.3 on 2024-12-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilesMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_path_rw', models.CharField(max_length=255)),
                ('file_path_pr', models.CharField(blank=True, max_length=255, null=True)),
                ('file_path_pd', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.CharField(max_length=255)),
                ('parent_file_id', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Success'), (2, 'Failure')])),
                ('reason', models.TextField(blank=True, null=True)),
                ('file_state', models.IntegerField(choices=[(1, 'Raw'), (2, 'Processed'), (3, 'Predicted'), (4, 'Analytics')], default=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'filesmaster',
            },
        ),
    ]
