# Generated by Django 5.1.3 on 2024-12-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemasters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesmaster',
            name='merge_status',
            field=models.BooleanField(default=False),
        ),
    ]
