# Generated by Django 5.1.3 on 2024-12-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataColumnSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.IntegerField()),
                ('file_name', models.CharField(max_length=255)),
                ('column_name', models.CharField(max_length=255)),
                ('column_slug', models.SlugField(max_length=255, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
