# Generated by Django 5.1.3 on 2024-12-19 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datacolumnsettings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datacolumnsettings',
            name='file_id',
        ),
    ]
